---
- name: terminate Ec2 specified instances
  hosts: localhost
  connection: local
  gather_facts: False


  vars:
    region: us-east-1
    instance_ids:
      - i-039e389dc5aa97e4b
      - i-09dca7ad1b1451575
     


  tasks:
    - name: myTargetEc2instances
      ec2_instance:
        region: "{{ region }}"
        instance_ids: "{{ instance_ids }}"
        state: absent
